//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDR_RT_MANIFEST                 1
#define IDC_MODIFY_INSURE_PASSWORD      2
#define IDC_DEFAULT                     3
#define IDC_CLOSE_SERVER                4
#define IDC_CLOSE_PLAZA                 5
#define IDR_MAINFRAME                   128
#define IDD_DLG_SEARCH_TABLE            129
#define IDC_HAND_CUR                    130
#define IDB_BT_CERTIFICATE              131
#define IDB_BT_GAMELIST                 132
#define IDB_BT_GAMEMATCH                133
#define IDB_BT_GAMELIST1                134
#define IDB_BT_GAMEMATCH1               135
#define IDB_BT_CLOSE                    137
#define IDD_DLG_REGISTER                137
#define IDB_FRAME_TM                    142
#define IDB_FRAME_TR                    143
#define IDB_FRAME_TL                    144
#define IDB_FRAME_MR                    145
#define IDB_FRAME_ML                    146
#define IDB_FRAME_BM                    147
#define IDB_FRAME_BR                    148
#define IDD_GAME_PLAZA                  149
#define IDB_FRAME_BL                    149
#define IDB_BT_SKIN                     150
#define IDB_BT_MIN                      151
#define IDB_BT_MAX                      152
#define IDB_BT_RESORE                   153
#define IDB_SERVER_LIST_BL              154
#define IDB_SERVER_LIST_BM              155
#define IDB_SERVER_LIST_BR              156
#define IDB_SERVER_LIST_ML              157
#define IDB_SERVER_LIST_MR              158
#define IDB_SERVER_LIST_TL              159
#define IDB_SERVER_LIST_TM              160
#define IDB_SERVER_LIST_TR              161
#define IDB_ITEM_FRAME_BL               162
#define IDB_ITEM_FRAME_BM               163
#define IDB_ITEM_FRAME_BR               164
#define IDB_ITEM_FRAME_ML               165
#define IDB_ITEM_FRAME_MR               166
#define IDR_COMMAND                     166
#define IDB_ITEM_FRAME_TL               167
#define IDD_DLG_STATUS                  168
#define IDB_ITEM_FRAME_TM               168
#define IDB_ITEM_FRAME_TR               169
#define IDD_GAME_SERVER                 169
#define IDB_USER_INFO_BK                172
#define IDB_BROWSER_BL                  173
#define IDB_BROWSER_BM                  174
#define IDB_BROWSER_BR                  175
#define IDB_BROWSER_ML                  176
#define IDB_BROWSER_TM                  179
#define IDB_BROWSER_TR                  180
#define IDD_COLLOCATE                   181
#define IDD_COLLOCATE_SERVER            182
#define IDD_COLLOCATE_PROXY             183
#define IDB_BT_GOODNUM                  184
#define IDB_BT_VIPMEMBER                185
#define IDB_BT_MOBILEGAME               186
#define IDB_BT_BROWSER_HOME             187
#define IDB_ITEM_BUTTON                 188
#define IDB_BT_GET_PRIZE                189
#define IDB_BT_COMBOBOX                 193
#define IDB_SERVER_STATE_IMAGE          209
#define IDB_SERVER_LIST_IMAGE           210
#define IDD_DLG_DOWNLOAD                211
#define IDI_DOWNLOAD                    212
#define IDB_DOWN_LOAD_ITEM              213
#define IDB_BT_DOWN_LOAD_NEXT           215
#define IDB_BT_DOWN_LOAD_LAST           216
#define IDB_BK_GAME_LIST                217
#define IDB_TABLE_BL                    222
#define IDB_TABLE_BM                    223
#define IDB_TABLE_BR                    224
#define IDB_TABLE_ML                    225
#define IDB_TABLE_MR                    226
#define IDB_TABLE_TL                    227
#define IDB_TABLE_TM                    228
#define IDB_TABLE_TR                    229
#define IDB_BK_USER_LIST                242
#define IDB_USER_LIST_BL                243
#define IDB_USER_LIST_BM                244
#define IDB_USER_LIST_BR                245
#define IDB_USER_LIST_ML                246
#define IDB_USER_LIST_MR                247
#define IDB_USER_LIST_TL                248
#define IDB_USER_LIST_TM                249
#define IDB_USER_LIST_TR                250
#define IDB_CHAT_BL                     251
#define IDB_CHAT_BM                     252
#define IDB_CHAT_BR                     253
#define IDB_CHAT_ML                     254
#define IDB_CHAT_MR                     255
#define IDB_CHAT_TL                     256
#define IDB_CHAT_TM                     257
#define IDB_CHAT_TR                     258
#define IDB_TABLE_GROUND                260
#define IDB_BK_USER_INFO_1              282
#define IDB_BK_USER_INFO_2              283
#define IDB_BK_USER_INFO_4              284
#define IDB_BK_USER_INFO                285
#define IDB_BK_USER_MEILI               286
#define IDD_DLG_WHISPER                 287
#define IDB_BT_CLOSE_QQ                 288
#define IDB_BK_PLATFORM_1               290
#define IDB_BT_CLOSE_SERVER1            291
#define IDB_BT_CLOSE_SERVER             292
#define IDB_BT_QUIT_SERVER              293
#define IDB_BT_TABLE_BUTTON_1           294
#define IDB_BT_TABLE_BUTTON_2           295
#define IDB_BT_TABLE_BUTTON_3           296
#define IDB_BT_TABLE_BUTTON_4           297
#define IDB_BT_TABLE_BUTTON_5           298
#define IDB_BT_CHAT_BUTTON_1            302
#define IDB_BT_CHAT_BUTTON_2            303
#define IDB_BT_CHAT_BUTTON_3            304
#define IDB_BT_CHAT_BUTTON_4            305
#define IDB_BT_CHAT_SHORT               306
#define IDB_BT_SEND_CHAT                307
#define IDB_HISTORY_WHISPER_BL          308
#define IDB_HISTORY_WHISPER_BM          309
#define IDB_HISTORY_WHISPER_BR          310
#define IDB_HISTORY_WHISPER_ML          311
#define IDB_HISTORY_WHISPER_MR          312
#define IDB_HISTORY_WHISPER_TL          313
#define IDB_HISTORY_WHISPER_TM          314
#define IDB_HISTORY_WHISPER_TR          315
#define IDB_CHAT_WHISPER_BL             316
#define IDB_CHAT_WHISPER_BM             317
#define IDB_CHAT_WHISPER_BR             318
#define IDB_CHAT_WHISPER_ML             319
#define IDB_CHAT_WHISPER_MR             320
#define IDB_CHAT_WHISPER_TL             321
#define IDB_CHAT_WHISPER_TM             322
#define IDB_CHAT_WHISPER_TR             323
#define IDB_BK_LIST                     326
#define IDD_DLG_PROXY_CONFIG            328
#define IDB_BK_PLATFORM_2               328
#define IDD_DLG_LOCK_MACHINE            329
#define IDB_BK_PLATFORM_3               329
#define IDB_INPUT_WHISPER_BL            330
#define IDB_ENQUIRE_SERVER              331
#define IDB_ENQUIRE_SWITCH              332
#define IDB_ENQUIRE_PLAZA               333
#define IDB_INPUT_WHISPER_BR            337
#define IDB_INPUT_WHISPER_ML            338
#define IDB_INPUT_WHISPER_MR            339
#define IDB_INPUT_WHISPER_TL            340
#define IDB_INPUT_WHISPER_TM            341
#define IDB_GAME_PROPERTY_ITEM          343
#define IDB_GAME_PROPERTY_L             344
#define IDB_GAME_PROPERTY_M             345
#define IDB_GAME_PROPERTY_R             346
#define IDB_BK_USER_INFO_SET            349
#define IDD_DLG_SERVICE_BROWSER         350
#define IDB_SERVICE_LIST_IMAGE          353
#define IDB_INPUT_WHISPER_TR            354
#define IDB_INPUT_WHISPER_BM            355
#define IDB_BT_WHISPER_BUTTON_1         358
#define IDB_BT_WHISPER_BUTTON_2         359
#define IDB_BT_WHISPER_BUTTON_3         360
#define IDD_COLLOCATE_CUSTOM            361
#define IDD_COLLOCATE_SYSTEM            362
#define IDB_BT_WHISPER_HISTORY          364
#define IDD_COLLOCATE_NOTIFY            364
#define IDB_BT_WHISPER_SEND_CONTROL     366
#define IDI_WHISPER                     367
#define IDB_WHISPER_USER_INFO_T         368
#define IDB_WHISPER_USER_INFO_B         369
#define IDB_WHISPER_USER_INFO_M         370
#define IDB_WHISPER_CONTRUL_T           371
#define IDB_WHISPER_CONTRUL_B           372
#define IDB_WHISPER_CONTRUL_M           373
#define IDD_DLG_SERVICE                 384
#define IDB_BT_LOGON_LINK               384
#define IDD_DLG_LOGON                   385
#define IDB_BT_ALMS                     386
#define IDD_SKIN_CONTROL                387
#define IDB_BT_LOGON                    387
#define IDD_PASSWORD_KEYBOARD           388
#define IDB_BT_LOGON_QUIT               389
#define IDD_DLG_ENQUIRE                 391
#define IDB_BT_LOGON_ITEM               391
#define IDB_BT_ENQUIRE_CANCEL           392
#define IDB_IMAGE_REGISTER              396
#define IDD_DLG_TABLE_PASSWORD          397
#define IDB_BT_REGISTER                 399
#define IDB_BT_REGISTER_CLOSE           400
#define IDD_DLG_SEARCH_USER             414
#define IDB_BT_WHISPER_USER_MENU        415
#define IDB_IMAGE_SEARCH                417
#define IDB_REMOTE_USER_IMAGE           419
#define IDB_BT_STATUS_CANCEL            423
#define IDR_PNG1                        425
#define IDD_DLG_SERVER_MANAGER          426
#define IDD_DIALOG1                     427
#define IDD_COLLOCATE_ROOM              427
#define IDD_DLG_MANAGE_SERVER           429
#define IDB_SHIELD_WHISPER              431
#define IDD_DLG_MANAGE_USER             431
#define IDB_RECEVE_WHISPER              432
#define IDB_SET_FRIEND                  433
#define IDB_CANCEL_FRIEND               434
#define IDB_SET_DETEST                  435
#define IDB_CANCEL_DETEST               436
#define IDD_DLG_ISSUE_MESSAGE           438
#define IDB_MESSAGE_SETTING             439
#define IDD_DLG_KICK_USER               439
#define IDD_DLG_DISMISSGAME             440
#define IDB_MATCH_BT_JOIN               441
#define IDD_DIALOG_ALMS                 441
#define IDB_MATCH_BT_LEAVE              442
#define IDD_DIALOG2                     442
#define IDD_DIALOG_PASSVALIDATE         442
#define IDB_MATCH_TABLE_TL              443
#define IDD_DIALOG_MSGPOP               443
#define IDB_MATCH_TABLE_TM              444
#define IDD_DIALOG_MOBILEBIND           444
#define IDB_MATCH_TABLE_TR              445
#define IDD_DIALOG3                     445
#define IDD_DIALOG_QQLOGON              445
#define IDD_MBCARD                      450
#define IDB_BT_EXCHANGE                 451
#define IDB_BK_NAVIGATION1              452
#define IDD_VERIFY_INSUREPASS           453
#define IDB_BK_ROOM_ADV1                454
#define IDB_BK_ROOM_ADV2                455
#define IDB_BK_USER_INFO_COPY           458
#define IDB_BK_NAVIGATION2              459
#define IDB_BK_NAVIGATION3              460
#define IDB_BK_NAVIGATION4              461
#define IDB_BK_NAVIGATION5              462
#define IDB_PNG1                        466
#define IDB_BITMAP1                     468
#define IDB_BT_DAYSIGN                  468
#define IDD_DIALOG_LOCKMACHINE          469
#define IDD_DIALOG_PASSID               470
#define IDB_PNG3                        472
#define IDD_AUTHEN_DLG                  473
#define IDD_INPUT_DLG                   474
#define IDD_USERINFO_DLG                475
#define IDB_BITMAP3                     476
#define IDB_MATCH_TABLE_TT              476
#define IDB_BITMAP4                     477
#define IDC_SELECT_FACE                 1000
#define IDC_FACE_ITEM                   1001
#define IDC_SERVER_NAME                 1001
#define IDC_MOBILE_GAME                 1005
#define IDC_TABLE_PASSWORD              1006
#define IDC_NODE_ID                     1007
#define IDC_GET_PRIZE                   1008
#define IDC_WEB_HOME                    1009
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_DELETE_RECORD               1010
#define IDC_SEARCH_ONE_NULL             1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_GIVE_UP                     1011
#define IDC_REM_PASSWORD                1012
#define IDC_CANCEL_ONE                  1012
#define IDC_RETRY_AGAIN                 1013
#define IDC_REGISTER                    1013
#define IDC_SORT_ID                     1013
#define IDC_SEARCH_TWO_NULL             1014
#define IDC_AGREE_AGREEMENT             1015
#define IDC_STATIC_AGREEMENT            1016
#define IDC_SEARCH_NOT_FULL             1017
#define IDC_LOGON_GETPWD                1018
#define IDC_LOGON_REMPWD                1019
#define IDC_SEARCH_ALL_NULL             1019
#define IDC_PROXY_CONFIG                1020
#define IDC_LOGON_PASS1                 1020
#define IDC_GOOD_NUM                    1021
#define IDC_TAB_CONTROL                 1021
#define IDC_INSURE_PASS1                1021
#define IDC_CHAT_INPUT                  1022
#define IDC_BT_LOGON_LINK_4             1022
#define IDC_FILTRATE_PASS               1022
#define IDC_KIND_ID                     1022
#define IDC_DOWNLOAD_DX                 1023
#define IDC_VIP_MEMBER                  1024
#define IDC_GAME_ID                     1024
#define IDC_LOGON_UNBUNDLING            1025
#define IDC_MODE_NAME                   1026
#define IDC_QUIT                        1026
#define IDC_RESTRICT_SCORE              1026
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_VALIDATE_CODE_WND           1028
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_BT_USER_MENU                1029
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_USER_LIST_CONTROL           1030
#define IDC_REVENUE_RATIO               1030
#define IDC_SERVICE_REVENUE             1030
#define IDC_PROXY_TEST                  1031
#define IDC_SEARCH_AREA                 1031
#define IDC_REVENUE_RATIO2              1031
#define IDC_SERVICE_SCORE               1031
#define IDC_REVENUE_RADIO               1031
#define IDC_SEARCH_REMOTE               1032
#define IDC_PROXY_TYPE                  1033
#define IDC_GENDER_MANKIND              1033
#define IDC_SEARCH_BY_GAME_ID           1033
#define IDC_PROXY_SERVER                1034
#define IDC_GENDER_FEMALE               1034
#define IDC_SEARCH_NAME                 1034
#define IDC_CHAT_MESSAGE                1035
#define IDC_CHANGE_VALIDATE             1035
#define IDC_STATIC_IMAGE                1035
#define IDC_PROXY_USER                  1036
#define IDC_USER_LIST_REMOTE            1036
#define IDC_VIEW_CONTROL                1037
#define IDC_USER_LIST_NATIVE            1037
#define IDC_PROXY_PORT                  1038
#define IDC_DOWNLOAD_WT                 1039
#define IDC_PROXY_PASS                  1040
#define IDC_RICHEDIT21                  1040
#define IDC_EDT_HISTORY                 1040
#define IDC_ADD_FRIEND                  1041
#define IDC_SET_DETEST                  1042
#define IDC_SHIELD_THIS_CHAT            1044
#define IDC_BT_QUIT_SERVER              1045
#define IDC_BUTTON4                     1045
#define IDC_MESSAGE_SETTING             1045
#define IDC_BT_TABLE_BUTTON_5           1046
#define IDC_BT_TABLE_BUTTON_4           1047
#define IDC_BT_TABLE_BUTTON_1           1049
#define IDC_AUTO_JOIN                   1049
#define IDC_ISSUE_MESSAGE               1049
#define IDC_BT_TABLE_BUTTON_2           1050
#define IDC_DISMISS_GAME                1050
#define IDC_BT_TABLE_BUTTON_3           1051
#define IDC_SEE_USER_IP                 1051
#define IDC_CHECK_ALLROOM               1052
#define IDC_EDIT_TALBER_NUM             1053
#define IDC_EDIT_TABLE_NUM              1053
#define IDC_TAKE_PASSWORD               1054
#define IDC_INPUT                       1054
#define IDC_STATIC_SERVER               1054
#define IDC_CHAT_EDIT                   1055
#define IDC_STATIC_PASS                 1055
#define IDC_BT_SEND_CHAT                1056
#define IDC_BUTTON1                     1056
#define IDC_BUTTON_PASSID               1056
#define IDC_BUTTON_ALMS                 1056
#define IDC_BUTTON_MSGPOP               1056
#define IDC_BUTTON_VERIFYPASS           1056
#define IDC_BTN_NUM1                    1056
#define IDC_ACCOUNTS                    1057
#define IDC_BUTTON_PASSVALI             1057
#define IDC_STATIC_PC                   1057
#define IDC_BTN_NUM2                    1057
#define IDC_LOGON_SERVER                1058
#define IDC_NICKNAME                    1058
#define IDC_EDIT_PASS_VALIDATE          1058
#define IDC_EDIT_NAME                   1058
#define IDC_BTN_NUM3                    1058
#define IDC_PASSWORD                    1059
#define IDC_STATIC_PASSVALI             1059
#define IDC_BTN_NUM4                    1059
#define IDC_BT_CHAT_BUTTON_1            1060
#define IDC_QQ                          1060
#define IDC_LOGON_PASSWORD2             1060
#define IDC_EDIT2                       1060
#define IDC_EDIT_PASSID                 1060
#define IDC_BTN_NUM5                    1060
#define IDC_SEAT_PHONE                  1061
#define IDC_LOGON_PASSWORD3             1061
#define IDC_LOGON_PASS2                 1061
#define IDC_STATIC_PASSID               1061
#define IDC_BTN_NUM6                    1061
#define IDC_BT_CHAT_BUTTON_2            1062
#define IDC_MOBILE_PHONE                1062
#define IDC_INSURE_PASSWORD2            1062
#define IDC_INSURE_PASS2                1062
#define IDC_STATIC_NAME                 1062
#define IDC_BTN_NUM7                    1062
#define IDC_PASSPORT_ID                 1063
#define IDC_EMAIL                       1063
#define IDC_INSURE_PASSWORD3            1063
#define IDC_STATIC_PID                  1063
#define IDC_BTN_NUM8                    1063
#define IDC_BT_CHAT_BUTTON_3            1064
#define IDC_SPREADER                    1064
#define IDC_DWELLING_PLACE              1064
#define IDC_PASSWORD2                   1064
#define IDC_BTN_NUM9                    1064
#define IDC_LAST                        1065
#define IDC_COMPELLATION                1065
#define IDC_STATIC_PWD1                 1065
#define IDC_BTN_NUM10                   1065
#define IDC_BT_CHAT_BUTTON_4            1066
#define IDC_VALIDATE_CODE               1066
#define IDC_USER_NOTE                   1066
#define IDC_STATIC_PWD2                 1066
#define IDC_BTN_NUM11                   1066
#define IDC_NEXT                        1067
#define IDC_STATIC_PASS_REMARK          1067
#define IDC_PASSWORDPRETECT             1068
#define IDC_PASSWORDPROTECT             1068
#define IDC_STATIC_PASSWORD_PROTECT     1069
#define IDC_STATIC_ALMS                 1070
#define IDC_VOR_SPLITER                 1071
#define IDC_STATIC_WEBDOWN              1071
#define IDC_STATIC_WEBDOWN1             1072
#define IDC_HOR_SPLITER                 1073
#define IDC_BUTTON_LOGON_QQ             1073
#define IDC_EXPLORER_QQ                 1074
#define IDC_INSURELOCK_QQ               1075
#define IDC_STATIC_                     1076
#define IDC_STATIC_INPWD                1076
#define IDC_BT_DAYSIGN_IN               1077
#define IDC_BT_EXCHANGE                 1078
#define IDC_LIMIT_SAME_IP               1079
#define IDC_INSURE_PASSWORD             1079
#define IDC_VERIFY_PASSWORD             1079
#define IDC_SWITCH_ACCOUNTS             1080
#define IDC_STATIC_GETPWD               1080
#define IDC_LIMIT_FLEE_RATE             1081
#define IDC_BT_CHAT_SHORT               1082
#define IDC_RADIO_VERIFY1               1082
#define IDC_LIMIT_GAME_SCORE            1083
#define IDC_RADIO_VERIFY2               1083
#define IDC_BT_CHAT_HISTORY             1084
#define IDC_RADIO_VERIFY3               1084
#define IDC_STATIC_MINUTE               1086
#define IDC_VERIFYPASS_TITLE            1087
#define IDC_LIMIT_DETEST                1088
#define IDC_COMBO1                      1088
#define IDC_COMBO_MINUTE                1088
#define IDC_BT_SEND_CONTROL             1089
#define IDC_STATIC_PASSTITLE            1089
#define IDC_LIMIT_WIN_RATE              1090
#define IDC_VERIFY_INSUREPWD_QQ         1090
#define IDC_CHAT_SPLITTER               1091
#define IDC_WIN_RATE                    1092
#define IDC_ED_TIMERATE                 1092
#define IDC_CTRPASSWORD                 1092
#define IDC_INFO_SPLITTER               1093
#define IDC_CONCLUDETIME                1093
#define IDC_EDIT_NUM                    1093
#define IDC_STA_GETPIC                  1094
#define IDC_GAME_SCORE_MIN              1095
#define IDC_EDIT_CHECKNUM               1095
#define IDC_BTN_DEL                     1096
#define IDC_BTN_RESET                   1097
#define IDC_EDIT1                       1098
#define IDC_STATIC_REG_ACCOUNTS         1099
#define IDC_STATIC_REG_NICKNAME         1100
#define IDC_STATIC_REG_LOGINPASS1       1101
#define IDC_STATIC_REG_PASSPORTID       1102
#define IDC_STATIC_INSURE1              1103
#define IDC_STATIC_INSURE2              1104
#define IDC_STATIC_REG_LOGINPASS2       1105
#define IDC_STATIC_REG_INSUREPASS1      1106
#define IDC_STATIC_REG_INSUREPASS2      1107
#define IDC_MESSAGE_SHOW_ALL            1108
#define IDC_MESSAGE_ONLY_FRIEND         1109
#define IDC_LIMIT_WISPER                1110
#define IDC_MESSAGE_HIDE_DETEST         1111
#define IDC_LIMIT_ROOM_CHAT             1112
#define IDC_INVITE_ALL                  1113
#define IDC_LIMIT_ENTER_GAME            1114
#define IDC_INVITE_ONLY_FRIEND          1115
#define IDC_LIMIT_PLAY_CHAT             1115
#define IDC_LIMIT_GAME_CHAT             1116
#define IDC_GAME_SCORE_MAX              1117
#define IDC_LIMIT_REMOTE_SEARCH         1117
#define IDC_INVITE_NONE                 1118
#define IDC_LIMIT_ENTER_ANDROID         1118
#define IDC_LIMIT_ENTER_ROOM            1119
#define IDC_AUTO_SHOW_WHISPER           1120
#define IDC_FORBID_MEMBER_CAN_CHAT      1120
#define IDC_SHOW_WHISPER_BY_HOTKEY      1121
#define IDC_FORBID_LOOKON               1121
#define IDC_WHISPER_HOTKEY              1122
#define IDC_FORBID_LOOKON_CHAT          1122
#define IDC_NOTIFY_USER_INOUT           1123
#define IDC_ALLOW_LOOKON_CHAT           1123
#define IDC_ALLOW_SOUND                 1124
#define IDC_FULL_SCREEN_BROWSE          1125
#define IDC_SNED_WHISPER_BY_ENTER       1126
#define IDC_ALLOW_BACKMUSIC             1126
#define IDC_ALLOW_MEMBER_LOOKON_CHAT    1126
#define IDC_AUTO_SAVE_WHISPER           1127
#define IDC_SNED_WHISPER_BY_CTRL_ENTER  1128
#define IDC_AUTO_SIT_DOWN               1129
#define IDC_ALLOW_WISPER                1130
#define IDC_SALIENCE_TABLE              1131
#define IDC_ALLOW_ROOM_CHAT             1132
#define IDC_NOTIFY_FRIEND_COME          1133
#define IDC_ALLOW_ENTER_GAME            1134
#define IDC_BOSS_HOTKEY                 1135
#define IDC_ALLOW_PLAY_CHAT             1135
#define IDC_ALLOW_GAME_CHAT             1136
#define IDC_ACTION_SEND_WHISPER         1137
#define IDC_ALLOW_REMOTE_SEARCH         1137
#define IDC_ALLOW_ENTER_ROOM            1138
#define IDC_ALLOW_ENTER_ANDROID         1139
#define IDC_ACTION_SHOW_USER_INFO       1140
#define IDC_ALLOW_MEMBER_CAN_CHAT       1140
#define IDC_ACTION_SEARCH_TABLE         1141
#define IDC_ALLOW_LOOKON                1141
#define IDC_SHOW_SEARCH_TABLE_DLG       1142
#define IDC_ACTION_ORIENTATION          1143
#define IDC_FLEE_RATE                   1158
#define IDC_UNDER_WRITE                 1168
#define IDC_LOGON_PASSWORD1             1181
#define IDC_INSURE_PASSWORD1            1182
#define IDC_MODIFY_LOGON_PASSWORD       1183
#define IDC_NOTE                        1184
#define IDC_LOGONPWD_QQ                 1185
#define IDC_INSUREPWD_QQ                1186
#define IDC_KICK_ALL_USER               1191
#define IDC_EDT_MESSAGE                 1192
#define IDC_CHEK_GAME                   1197
#define IDC_CHEK_ROOM                   1198
#define IDC_CHEK_LOOP                   1199
#define IDC_STRING                      1201
#define IDB_BITMAP2                     1202
#define IDC_STC_ACCOUNT                 1225
#define IDC_STC_ID                      1226
#define IDC_STC_RANK                    1227
#define IDC_STC_SCORE                   1228
#define IDC_STC_WINNUM                  1231
#define IDC_STC_LOSTNUM                 1232
#define IDC_STC_TIENUM                  1233
#define IDC_STC_FLEE                    1234
#define IDC_STC_LOSTRATE                1236
#define IDC_STC_WINRATE                 1237
#define IDC_STATIC_SCORE                1238
#define IDC_TAB_FACE                    2002
#define IDD_DLG_COSTOM_FACE             3000
#define IDD_DLG_SERVICE_INDIVIDUAL      3001
#define IDD_DLG_SERVICE_PASSWORD        3002
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDC_FORFEND_ROOM_CHAT           9004
#define IDC_FORFEND_WISPER_CHAT         9005
#define IDC_FORFEND_GAME_CHAT           9006
#define IDC_DYNAMIC_JOIN                9007
#define IDC_ALLOW_DYNAMIC_JOIN          9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDC_OFFLINE_TRUSTEE             9010
#define IDC_ALLOW_OFFLINE_TRUSTEE       9010
#define IDC_AVERT_CHEAT_MODE            9011
#define IDC_ALLOW_AVERT_CHEAT_MODE      9011
#define IDC_ALLOW_ANDROID_USER          9012
#define IDC_ALLOW_ANDROID_ATTEND        9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_FORFEND_LOCK_TABLE          9016
#define IDC_FORFEND_SAVE_IN_GAME        9017
#define IDC_FORFEND_SAVE_IN_ROOM        9018
#define IDC_FORBID_WINRATE              9019
#define IDC_ALLOW_ANDROID_SIMULATE      9019
#define IDC_FORBID_FLEERATE             9020
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDC_FORBID_SCORELIMIT           9021
#define IDC_FORBID_BLACK                9022
#define IDC_STATIC_REVENUE_SERVICE      9022
#define IDC_FORBID_IPSET                9023
#define IDC_SERVICE_RADIO               9024
#define IDC_FORBID_PASSWORD             9025
#define IDM_USER_LOGON                  32774
#define IDM_SWITCH_ACCOUNTS             32778
#define IDM_COPY_USER_NICKNAME          32779
#define IDM_SEE_USER_LOCATION           32780
#define IDM_CREATE_ISER_WISPER          32781
#define IDM_ENTER_SERVER                32784
#define IDM_ENTER_TABLE                 32785
#define IDM_EXPAND_LIST                 32788
#define IDM_SHRINK_LIST                 32790
#define IDM_MESSAGE_HIDE_DETEST         32791
#define IDM_MESSAGE_SHOW_ALL            32792
#define IDM_MESSAGE_ONLY_FRIEND         32793
#define IDM_DELETE_SERVER_ITEM          32794
#define IDM_MANAGER_MESSAGE             32795
#define IDM_GAME_RULE                   32798
#define IDM_GAME_CHART                  32799
#define IDM_SET_FRIEND_USER             32801
#define IDM_SET_DETEST_USER             32802
#define IDM_NULL_COMMAND                32803
#define ID_Menu                         32804
#define ID_Menu32805                    32805
#define IDM_CANCEL_CHAT_USER            32819
#define IDM_SET_CHAT_USER               32820
#define IDM_SEARCH_ONLINE_USER          32821
#define IDM_INVITE_USER                 32822
#define IDM_SHOW_USER_INFO              32826
#define IDM_SET_USER_NOTE               32827
#define IDM_USER_INFO_MANAGER           32830
#define IDM_LOOKON_USER                 32832
#define IDM_PLAY_GAME_TOGETHER          32834
#define IDM_SEND_BY_ENTER               32837
#define IDM_SEND_BY_CTRL_ENTER          32838
#define IDM_MORE_COLOR                  32840
#define IDM_SEARCH_TABLE                32844
#define IDM_ISSUE_MESSAGE               32858
#define IDM_MANAGER_SERVER              32859
#define IDM_MANAGER_USER                32872
#define IDM_KILL_USER                   32874
#define IDM_LIMIT_USER_ROOM_CHAT        32892
#define IDM_ALLOW_USER_ROOM_CHAT        32894
#define IDM_LIMIT_USER_GAME_CHAT        32896
#define IDM_LIMIT_USER_WHISP_CHAT       32899
#define IDM_ALLOW_USER_WHISP_CHAT       32901
#define IDM_ALLOW_USER_GAME_CHAT        32902

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        478
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
