//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShareControl.rc
//
#define IDC_MODIFY_INSURE_PASSWORD      2
#define IDD_PASSWORD_KEYBOARD           388
#define IDD_INSURE_MAIN                 424
#define IDC_BT_SAVE_SCORE               1018
#define IDC_BT_QUERY_SAVE               1019
#define IDC_SCORE                       1039
#define IDC_USER_NICKNAME               1040
#define IDC_NICKNAME                    1040
#define IDC_SCORE_SAVE2                 1040
#define IDC_PASSWORD                    1059
#define IDC_INSURE_PASSWORD2            1062
#define IDC_INSURE_PASSWORD3            1063
#define IDC_INSURE_PASSWORD1            1182
#define IDD_MESSAGE_BOX                 2000
#define IDC_SCORE_STRING                2000
#define IDC_TAB_CONTROL                 2001
#define IDB_BT_QUERY_INFO               2002
#define IDC_FORGET_INSURE               2003
#define IDB_CHAT_CONTROL_BACK           2004
#define IDC_BT_TRANSFER_SCORE           2004
#define IDB_BT_CHAT_HISTORY             2005
#define IDC_BY_ID                       2005
#define IDB_BT_CHAT_CLOSE               2006
#define IDC_BY_NAME                     2006
#define IDD_BROWSER                     2007
#define IDC_TRAN5                       2007
#define IDB_BT_KEYBOARD                 2008
#define IDC_INSURE_SAVENUM1             2008
#define IDC_BT_TRANSFER_SCORE2          2008
#define IDC_BT_QUERY_TRANSFER           2008
#define IDB_BT_KEYBOARD_CLOSE           2009
#define IDC_INSURE_SAVENUM2             2009
#define IDB_KEYBOARD_ITEM1              2010
#define IDC_INSURE_SAVENUM3             2010
#define IDB_KEYBOARD_ITEM2              2011
#define IDC_INSURE_SAVENUM4             2011
#define IDB_KEYBOARD_ITEM3              2012
#define IDC_INSURE_SAVENUM5             2012
#define IDB_PASSWORD_KEYBORAD_BK        2013
#define IDC_INSURE_SAVENUM6             2013
#define IDC_INSURE_SAVENUM7             2014
#define IDC_INSURE_TRANNUM1             2016
#define IDC_INSURE_TRANNUM2             2017
#define IDC_INSURE_TRANNUM3             2018
#define IDC_INSURE_TRANNUM4             2019
#define IDC_INSURE_TRANNUM5             2020
#define IDC_INSURE_TRANNUM6             2021
#define IDB_IMAGE_TRUMPET               2022
#define IDC_TREE_SAFA                   2022
#define ID_CLOSE                        2022
#define IDB_BITMAP1                     2023
#define IDB_IMAGE_TYPHON                2023
#define IDC_TELLER1                     2023
#define IDC_EDIT1                       2023
#define IDC_EDIT_TRAN1                  2023
#define IDD_SAFA_PASSWORD               2024
#define IDC_TELLER2                     2024
#define IDD_INSURE_TELLER               2025
#define IDC_TELLER3                     2025
#define IDC_GROUP_INSURELOG             2025
#define IDC_TRAN4                       2026
#define IDD_DIALOG1                     2026
#define IDD_DIALOG_INSURE_LOG           2026
#define IDC_COMBO_LOGDATA                2026
#define IDC_TELLER5                     2027
#define IDC_TRAN6                       2027
#define IDC_STATIC_LOGTIP               2027
#define IDC_TELLER6                     2028
#define IDC_STATIC_LOGDATE              2028
#define IDC_TELLER_INSUREPWD            2029
#define IDC_BUTTON_QUERY                2029
#define IDC_BUTTON_TELLER               2030
#define IDC_EDIT_TELLER                 2031
#define IDC_LIST_TRANSFER_LOG           2031
#define IDC_TELLER_NUM1                 2032
#define IDC_STATIC_PAGE                 2032
#define IDC_TELLER_NUM2                 2033
#define IDC_BUTTON_BEFORE               2033
#define IDC_TELLER_NUM3                 2034
#define IDC_BUTTON_NEXT                 2034
#define IDC_TELLER_NUM4                 2035
#define IDC_BUTTON4                     2035
#define IDC_BUTTON_FIRST                2035
#define IDC_TELLER_NUM5                 2036
#define IDC_BUTTON_LAST                 2036
#define IDC_TELLER_NUM6                 2037
#define IDC_TELLER_NUM7                 2038
#define IDC_BT_QUERY_TELLER             2039
#define IDC_SAVE1                       2040
#define IDC_EDIT_TELLER2                2040
#define IDC_SAVE2                       2041
#define IDC_SAVE3                       2042
#define IDC_SAVE4                       2043
#define IDC_SAVE5                       2044
#define IDC_TRAN1                       2045
#define IDC_TRAN2                       2046
#define IDC_TRAN3                       2047
#define IDD_INSURE_SUCCESS              2048
#define IDC_SELECT                      3003
#define IDC_CHAT_SHORT_LIST             3004
#define IDD_EXPRESSION                  3009
#define IDC_HAND_CUR                    3010
#define IDD_INSURE_SAVE                 3010
#define IDD_INSURE_TRANSFER             3011
#define IDD_DLG_SERVICETRANSFER         3012
#define IDB_USER_STATUS_IMAGE           3013
#define IDB_IMAGE_AFFICHE               3017
#define IDB_IMAGE_PROMPT                3018
#define IDB_IMAGE_SYSTEM                3019
#define IDB_IMAGE_SELBANK               3020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2027
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2037
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
